spring:
  datasource:
    driverClassName: org.postgresql.Driver
  #com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATABASE_URL:}
  #"jdbc:mysql://localhost:3306/euphoria_gifts_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${JDBC_DATABASE_USERNAME:}
  #root
    password: ${JDBC_DATABASE_PASSWORD:}
  #1234

  sql:
    init:
      mode: never  #first time always, after running the app change to never

  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialecthow-sql=true
    hibernate:
      ddl-auto: create #first time create, after running the app change to validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

#Cloudinary Properties
cloudinary:
  api-key: 224294868543328
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: ddktqessk

     server:
       port: ${PORT:8080}
 # 8000
app:
  default:
    admin:
      password: admin

schedulers:
  cron: "* 00 07 1 * *"


  
  spring.datasource.hikari.connection-timeout=30000
  spring.datasource.hikari.maximum-pool-size=10
  
  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
