-- -- INSERT ROLES -------------------------------------------

INSERT INTO roles (id, name)
VALUES (1, 'ADMIN'),
       (2, 'USER');

-- -- INSERT USERS -------------------------------------------

INSERT INTO users (id, age, email, first_name, last_name, password, username)
VALUES (1, 20, 'admin@example.com', 'Admin', 'Adminov',
        '23b95ca352fe19b348e8f1b5a5a1cc1e23c54910ae9a89a35234f1e4791426e0b4af400a98cabb2e',
        'admin'),
       (2, 18, 'user@example.com', 'User', 'Userov',
        'faece043d5eac617582f4dd2cde7e2849606c5294c938d1eae7b4778018904b0eaab4846cff44d78',
        'user');

-- -- INSERT USERS_ROLES -------------------------------------------
INSERT INTO users_roles (user_entity_id, roles_id)
VALUES (1, 1),
       (1, 2),
       (2, 2);


INSERT INTO pictures (id, public_id, title, url)
VALUES (1, 'Bicycle_mysd5b', 'BicycleClock',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338295/Home/Clocks/Bicycle_mysd5b.jpg'),
       (2, 'Keys_kpwqy4', 'KeysHolder',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338293/Home/Jewelry%20and%20Key%20boxes/Keys_kpwqy4.jpg'),
       (3, 'HomeKeyBox_pqhcd0', 'HomeKeyBox',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338293/Home/Jewelry%20and%20Key%20boxes/HomeKeyBox_pqhcd0.jpg'),
       (4, 'GoldenCandlestick_xqwmd0', 'GoldenCandlestick',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338295/Home/Candlesticks%20and%20Candles/GoldenCandlestick_xqwmd0.jpg'),
       (5, 'HomeSweetHomeCandle_vddzqg', 'HomeSweetHomeCandle',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338295/Home/Candlesticks%20and%20Candles/HomeSweetHomeCandle_vddzqg.jpg'),
       (6, 'RoseCandle_cikwtm', 'RoseCandle',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338295/Home/Candlesticks%20and%20Candles/RoseCandle_cikwtm.jpg'),
       (7, 'RoseCandlestick_yrnre2', 'Rose Candlestick',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338295/Home/Candlesticks%20and%20Candles/RoseCandlestick_yrnre2.jpg'),
       (8, 'SeaWorldCandlestick_wyy5cz', 'SeaWorldCandlestick',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338295/Home/Candlesticks%20and%20Candles/SeaWorldCandlestick_wyy5cz.jpg'),
       (9, 'SummerMorningCandle_gphbxw', 'SummerMorningCandle',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338295/Home/Candlesticks%20and%20Candles/SummerMorningCandle_gphbxw.jpg'),
       (10, 'AshtraySceleton_sq5oum', 'AshtraySceleton',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338284/Home/Ashtrays/AshtraySceleton_sq5oum.jpg'),
       (11, 'AshtrayBlackDiamond_sht5fj', 'AshtrayBlackDiamond',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338284/Home/Ashtrays/AshtrayBlackDiamond_sht5fj.jpg'),
       (12, 'AshtrayWhiteDiamond_lagfpt', 'AshtrayWhiteDiamond',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1658338284/Home/Ashtrays/AshtrayWhiteDiamond_lagfpt.jpg'),
       (13, 'Dining_set_-_19_pieces_from_the_Poppy_series_irg9dg', 'DiningSet19',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Dining_set_-_19_pieces_from_the_Poppy_series_irg9dg.jpg'),
       (14, 'Dining_set_Grey_magic_-_16_psc_csydvz', 'DiningSetGreyMagic',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Dining_set_Grey_magic_-_16_psc_csydvz.jpg'),
       (15, 'Dining_set_Dandelion_-_19_pieces_n5od7l', 'DiningSetDandelion',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Dining_set_Dandelion_-_19_pieces_n5od7l.jpg'),
       (16, 'Decorative_plate_Hanna_vsamgj', 'DecorativePlateHanna',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Decorative_plate_Hanna_vsamgj.jpg'),
       (17, 'Plate_with_handles_Black_Marble_xmspwx', 'PlateBlackMarble',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Plate_with_handles_Black_Marble_xmspwx.jpg'),
       (18, 'Health_cheese_platter_with_utensils_xryg1l', 'CheesePlatterWithUtensils',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Health_cheese_platter_with_utensils_xryg1l.jpg'),
       (19, 'Set_of_kitchen_knives_-_GORIS_dpynjp', 'SetKitchenKnives',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Set_of_kitchen_knives_-_GORIS_dpynjp.jpg'),
       (20, 'Set_of_metal_boxes_Round_mkt43q', 'SetMetalBoxes',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Set_of_metal_boxes_Round_mkt43q.jpg'),
       (21, 'Small_glass_bowl_-_Freshness_abslce', 'GlassBowl',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Small_glass_bowl_-_Freshness_abslce.jpg'),
       (22, 'Red_wine_glasses_Silvia_red_bhttyh', 'RedWineGlasses',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Red_wine_glasses_Silvia_red_bhttyh.jpg'),
       (23, 'Sushi_set_Stone_and_Wood_zaabu0', 'SushiSet',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344781/KITCHEN/Sushi_set_Stone_and_Wood_zaabu0.jpg'),
       (24, 'Glass_Cake_Set_npluwx', 'GlassCakeSet',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344780/KITCHEN/Glass_Cake_Set_npluwx.jpg'),
       (25, 'Flower_box_Floral-collapsible_huaesk', 'FlowerBoxFloral',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344811/WOMEN/Flower_box_Floral-collapsible_huaesk.jpg'),
       (26, 'Flowerpot_Floral-mini_wheel_noxaox', 'FlowerpotFloralMiniWheel',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344811/WOMEN/Flowerpot_Floral-mini_wheel_noxaox.jpg'),
       (27, 'Jewelry_box_Rose_eekmiz', 'RoseJewelryBox',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344812/WOMEN/Jewelry_box_Rose_eekmiz.jpg'),
       (28, 'ParisMusicJewelryBox_hn0fcv', 'ParisJewelryMusicBox',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344812/WOMEN/ParisMusicJewelryBox_hn0fcv.jpg'),
       (29, 'Decorative_flower_pot_-_Bicycle_gabxfs', 'DecorativeFlowerPotBicycle',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344811/WOMEN/Decorative_flower_pot_-_Bicycle_gabxfs.jpg'),
       (30, 'Solar_lamp_-_Hedgehog_tkcx3l', 'SolarLampHedgehog',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344812/WOMEN/Solar_lamp_-_Hedgehog_tkcx3l.jpg'),
       (31, 'Ceramic_vase_from_the_Hana_series_-_23_cm_rl5db6', 'CeramicVaseHana',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344811/WOMEN/Ceramic_vase_from_the_Hana_series_-_23_cm_rl5db6.jpg'),
       (32, 'Photo_frame_-_Me_and_you_gaocoa', 'PhotoFrameMeAndYou',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344812/WOMEN/Photo_frame_-_Me_and_you_gaocoa.jpg'),
       (33, 'Photo_frame-collage_Romantic_world_kqwefl', 'PhotoFrame-CollageRomanticWorld',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344812/WOMEN/Photo_frame-collage_Romantic_world_kqwefl.jpg'),
       (34, 'Gift_mug_-_Panda_tqavrr', 'GiftMugPanda',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344811/WOMEN/Gift_mug_-_Panda_tqavrr.jpg'),
       (35, 'Gift_cup_-_Miracle_e5evjy', 'GiftCupMiracle',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344811/WOMEN/Gift_cup_-_Miracle_e5evjy.jpg'),
       (36, 'Picnic_basket_for_two_with_Accessories_on0co7', 'PicnicBasketWithAccessories',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344812/WOMEN/Picnic_basket_for_two_with_Accessories_on0co7.jpg'),
       (37, 'Compact_Wooden_Chess_-_Medium_cbemlp', 'CompactWoodenChess',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Compact_Wooden_Chess_-_Medium_cbemlp.jpg'),
       (38, 'Wooden_chess_and_flask_nr3xqc', 'WoodenChessAndFlask',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Wooden_chess_and_flask_nr3xqc.jpg'),
       (39, 'Decorative_figurine_-_Lion_j5gnuc', 'DecorativeFigurineLion',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Decorative_figurine_-_Lion_j5gnuc.jpg'),
       (40, 'Wall_decoration_-_Large_deer_dugcvj', 'WallDecorationLargeDeer',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Wall_decoration_-_Large_deer_dugcvj.jpg'),
       (41, 'Decorative_figurine_Elephant_with_ornaments_gcjuce', 'DecorativeFigurineElephant',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Decorative_figurine_Elephant_with_ornaments_gcjuce.jpg'),
       (42, 'Wine_rack_-_Boat_p84hz8', 'WineRackBoat',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Wine_rack_-_Boat_p84hz8.jpg'),
       (43, 'Wine_accessories_Labels_xj5jiu', 'WineAccessoriesLabels',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Wine_accessories_Labels_xj5jiu.jpg'),
       (44, 'Gift_cup_Knight_with_swords_hbnquo', 'GiftCupKnight',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Gift_cup_Knight_with_swords_hbnquo.jpg'),
       (45, 'Gift_cup_-_Pistol_ifvoyn', 'GiftCupPistol',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Gift_cup_-_Pistol_ifvoyn.jpg'),
       (46, 'Gift_set_-_Men_in_black_ylvocl', 'GiftSetMenInBlack',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Gift_set_-_Men_in_black_ylvocl.jpg'),
       (47, 'Desk_set_Lux_b9485c', 'DeskSetLux',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Desk_set_Lux_b9485c.jpg'),
       (48, 'Globe_bar_with_table_-_Worlds_o3zsov', 'GlobeBar',
        'https://res.cloudinary.com/ddktqessk/image/upload/v1660344858/MEN/Globe_bar_with_table_-_Worlds_o3zsov.jpg');
INSERT INTO gifts (id, description, name, price, quantity, category_id, picture_id)
VALUES (1,
        'Decorative bicycle clock with a classic design. Works with one AA 1.5V battery. It is available in several variants. Please specify your choice when ordering!',
        'Clock - Decorative bicycle', 60, 1, 1, 1),
       (2, 'Key holder from the KEYS series - house with space for four keys, made of wood. Suitable for every home.',
        'Key holder - House "Keys"', 32, 1, 1, 2),
       (3, 'Home hanger made of wood with metal hooks and spectacular decorative elements.',
        'Hanger - Home', 23, 1, 1, 3),
       (4,
        'Candlestick from the "Golden extravaganza" series, made of embossed glass with an original design. The set consists of a round candle holder suitable for a tea light and a small plate in the shape of a leaf.',
        'Golden Candlestick', 17, 1, 1, 4),
       (5, 'The aroma of roses favors achieving harmony in the home. Contributes to home comfort.',
        'Home Sweet Home Candle', 4.70, 1, 1, 5),
       (6, 'The three-layer candle with a light and delicate scent of rose favors the return of a good mood.',
        'Rose Candle', 7, 1, 1, 6),
       (7, 'Rose candlestick, made of polyresin and spectacularly decorated with gold brocade.',
        'Rose Candlestick', 8, 1, 1, 7),
       (8,
        'Decorative candlestick figurine from the Sea World series. Original candlestick in the shape of a seashell, a fish, a rudder and a starfish. Suitable decoration for both home and cafes, restaurants and hotels.',
        'Sea World Candlestick', 10, 1, 1, 8),
       (9, 'The candle creates a feeling of romance and tranquility, brings the freshness of quiet summer mornings.',
        'Summer Morning Candle', 4.70, 1, 1, 9),
       (10, 'Decorative ashtray "Skeleton" - made of polyresin.', 'Ashtray Sceleton', 15, 1, 1, 10),
       (11, 'Ashtray from the "Black Diamond" series - large, made of solid glass with an elegant shape.',
        'Ashtray Black Diamond', 65, 1, 1, 11),
       (12, 'Ashtray from the "Diamond" series - large, made of solid glass with an elegant shape.',
        'Ashtray White Diamond', 65, 1, 1, 12),
       (13,
        'Dining set - 19 pieces from the "Poppy Poppy" series on a black background. Contains six main plates, six soup plates, six dessert plates and one salad bowl. Comes in a colorful box.',
        'Dining set - 19 pieces', 180, 1, 2, 13),
       (14,
        'Dining service "Grey Magic" - 16 pieces. Contains four glasses, four large plates, four dessert plates and four bowls. Comes in a colorful box.',
        'Dining set Grey magic - 16 psc', 70, 1, 2, 14),
       (15,
        'Dining set - 19 pieces from the Dandelion series. Contains six dessert plates with a solid Dandelion decor in beautiful shades of green, six main, six deep plates and a salad bowl with an element of the main decor. Comes in a colorful box.',
        'Dining set Dandelion - 19 psc', 180, 1, 2, 15),
       (16,
        'Decorative plate from the Hanna series, suitable for decoration. A stylish gift for the home.',
        'Decorative plate Hanna', 43, 1, 2, 16),
       (17,
        'Plate with handles for serving from the Black Marble series, on a bamboo handle. Comes in a stylish colored box.',
        'Plate with handles Black Marble', 68, 1, 2, 17),
       (18,
        'Cheese plate with the inscription "Health". The set contains a bamboo platter with a cutlery holder, a porcelain bowl and two cheese knives. Comes in a stylish colored box.',
        'Health cheese platter with utensils', 64, 1, 2, 18),
       (19,
        'Set of kitchen knives on a rotating stand "GORIS Silver lines". It contains a cleaver, a large kitchen knife, a bread knife, a utility knife, a small knife, a peeler, a meat cleaver and a sharpener made of high-quality stainless steel.',
        'Set of kitchen knives - GORIS', 130, 1, 2, 19),
       (20,
        'Set of metal boxes "Circle". The set contains three boxes with lids suitable for storing coffee, sugar and tea.',
        'Set of metal boxes "Circle"', 24, 1, 2, 20),
       (21, 'Glass bowl - Freshness with spectacular decoration.', 'Small glass bowl - Freshness',
        5, 1, 2, 21),
       (22,
        'Red wine glasses from the Sylvia series. The set contains six glasses with an interesting design in red. A stylish and sophisticated gift suitable for any home. Offered in a luxurious box.',
        'Red wine glasses Silvia red', 92, 1, 2, 22),
       (23,
        'Sushi set "Stone and wood". Includes a stone table marked ''Sushi'', a wooden stand, two sauce bowls, a chopstick stand and two sets of chopsticks. Comes in a stylish chromatic box.',
        'Sushi set "Stone and Wood"', 27, 1, 2, 23),
       (24,
        'Glass cake set contains six small plates and one large one',
        'Glass Cake Set', 46, 1, 2, 24),
       (25,
        'Flowerpot from the Floral series, suitable for three pots.',
        'Flower box Floral-collapsible', 65, 1, 3, 25),
       (26,
        'Flowerpot from the Floral series, suitable for one pot.',
        'Flowerpot Floral-mini wheel', 38, 1, 3, 26),
       (27,
        'Jewelry box "Rose" made of artificial leather with practical compartments for different types of jewelry, a mirror located on the inside of the lid and a metal locking mechanism with keys. It is available in several variants. Please specify your choice when ordering!',
        'Rose jewelry box', 85, 1, 3, 27),
       (28,
        'Music box for jewelry, has two compartments for storing jewelry. There is a built-in mirror on the lid. The music part of the jewelry box is activated by rolling the trigger on the back of the box.',
        'Paris Jewelry Music Box', 36, 1, 3, 28),
       (29,
        'Decorative planter - Bicycle, suitable for one pot.',
        'Decorative flower pot - Bicycle', 20, 1, 3, 29),
       (30,
        'Solar lamp Hedgehog, with an attractive and fun design.',
        'Solar lamp - Hedgehog', 34, 1, 3, 30),
       (31,
        'Ceramic vase from the Hanna series with a non-standard shape. A stylish and sophisticated gift for every home.',
        'Ceramic vase Hana', 28, 1, 3, 31),
       (32,
        'Photo frame - collage, suitable for three photos 15*10cm, two photos 10*10cm and one photo 10*15cm.',
        'Photo frame - Me and you', 36, 1, 3, 32),
       (33,
        'Photo frame-collage Romantic world made of plastic, suitable for nine photos with a size of 10*15 cm.',
        'Photo frame-collage Romantic world', 28, 1, 3, 33),
       (34,
        '"Panda" gift cup with a lid, decorated with a silicone figurine and a metal spoon. It is available in several variants. Please refer to your selection when ordering.',
        'Gift mug - Panda', 21, 1, 3, 34),
       (35,
        'Gift cup "Miracle" with saucer and metal spoon. It is available in several variants. Please specify your choice when ordering.',
        'Gift cup - Miracle', 32, 1, 3, 35),
       (36,
        'Picnic basket for two "Accessories". Includes a picnic bag with thermal food compartment, two china plates, two Plexiglas glasses, two forks, two spoons, two knives and a corkscrew.',
        'Picnic basket with Accessories', 132, 1, 3, 36),
       (37,
        'Chess is a classic strategy game for two that increases mental capacity and logical thinking. It develops many qualities such as: attention, memory, concentration and analysis. It is combined with the backgammon where luck has more power, this set is suitable for every home and company. It is made of high quality wood and is an original gift for anyone who loves smart games and fun.',
        'Compact Wooden Chess - Medium', 39, 1, 4, 37),
       (38,
        'The set contains wooden chess pieces, a flask, a funnel and two cups in a compact wooden box. Chess is a classic and strategic game for two that increases mental capacity and logical thought.',
        'Wooden chess and flask', 50, 1, 4, 38),
       (39,
        'Decorative figurine from the Modern World series - Lion. The lion personifies strength, magnanimity and royal authority. According to Feng Shui, it carries honor, wisdom and freedom.',
        'Decorative figurine - Lion', 73, 1, 4, 39),
       (40,
        'Deer decorative figurine suitable for hanging. In Feng Shui, deer are associated with longevity, endurance, grace and kindness. In Chinese, the word deer sounds like the word for income and prosperity, making the graceful animal an amulet suitable for both home and office. Amazing decoration for hotel, lodge or restaurant.',
        'Wall decoration - Large deer', 160, 1, 4, 40),
       (41,
        'Decorative figurine Elephant with ornaments - large. The elephant is a symbol of strength and wisdom, invulnerability and royal authority. A very effective talisman for business, the elephant likes to be consulted and often patted on the trunk when a difficult decision is to be made.',
        'Decorative figurine Elephant', 55, 1, 4, 41),
       (42,
        'Wine rack Boat, with space for bottles and glasses. There is a storage cabinet in its lower part. A suitable gift for wine lovers and a spectacular decoration for cafes, restaurants and hotels.',
        'Wine rack - Boat', 999, 1, 4, 42),
       (43,
        '"Inscriptions" wine accessories. The set includes a corkscrew with opener, a bottle ring and a foil cutter in a stylish black box with lettering.',
        'Wine accessories Labels', 14, 1, 4, 43),
       (44,
        'Gift mug "Knight with swords". A spectacular mug made of polyresin with embossed images of a knight with crossed swords.',
        'Gift cup Knight with swords', 23, 1, 4, 44),
       (45,
        'Gift mug "Pistol". It is available in several variants. Please specify your choice when ordering.',
        'Gift cup - Pistol', 23, 1, 4, 45),
       (46,
        'The set contains a wallet, pen and belt. Comes in a box.',
        'Gift set - Men in black', 33, 1, 4, 46),
       (47,
        'Desk set Lux. It consists of a mirror-lacquered wooden base, on which is fixed a rotating globe with the continents and countries outlined and inscribed, a business card, a compartment with sticky notes and a pencil case. A stylish business gift suitable for any office.',
        'Desk set Lux', 130, 1, 4, 47),
       (48,
        'Globe bar "Worlds" with table. Movable globe bar with space for bottles at the bottom and space for bottles and glasses at the top. Painted with an antique map of the world on the outside and the kingdom of heaven on the inside. A perfect addition to the home or office.',
        'Globe bar with table - Worlds', 520, 1, 4, 48);
INSERT
INTO comments (is_approved, message, created_on, gift_entity_id, user_id)
values (true, 'Awesome gift', '2021-11-18 8:10:40', 1, 1),
       (true, 'Amazing gift', '2021-11-18 8:15:50', 1, 1);



